#!/usr/bin/env node
/**
 * Generates extension/styles/theme.css from web/app/globals.css.
 *
 * The two surfaces share one design system, but not one stylesheet: the web app
 * pulls tokens in through `@import "shadcn/tailwind.css"` and toggles dark mode
 * with a `.dark` class from next-themes, while the extension has neither
 * dependency and follows the OS theme. Until now theme.css was a hand-copy,
 * which is a promise nobody can keep — the first person to tweak a color in one
 * file silently splits the product in two.
 *
 *   node scripts/sync-theme.mjs           # rewrite theme.css
 *   node scripts/sync-theme.mjs --check   # exit 1 if it would change
 *
 * Three deliberate transforms, not a copy:
 *
 * 1. chart-* and sidebar-* tokens are dropped. The extension has no charts and
 *    no shadcn sidebar; carrying them would imply it does.
 * 2. font-* tokens are dropped from @theme. They resolve to next/font CSS
 *    variables that only exist on the web app's <html>.
 * 3. The .dark block is emitted as `:root[data-theme="dark"]`. The extension
 *    has no next-themes provider; a hand-rolled toggle (extension/lib/theme.ts)
 *    stamps data-theme on <html>, and light is the default. Deliberately NOT
 *    mirrored into a prefers-color-scheme query: the extension does not follow
 *    the OS theme.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const SOURCE = resolve(root, "web/app/globals.css")
const TARGET = resolve(root, "extension/styles/theme.css")

/**
 * Tokens the extension must not inherit, keyed on the name after `--` or
 * `--color-`. The `(?:-|$)` matters: the families include a bare `--sidebar`
 * and `--color-sidebar` alongside `--sidebar-primary` etc, and a trailing-
 * hyphen-only pattern lets those two through.
 */
const EXCLUDED = /^(?:color-)?(?:chart|sidebar|font)(?:-|$)/

/**
 * Returns the body of the top-level block whose header starts a line, brace-matched.
 *
 * Both halves of that sentence are load-bearing. Brace-matching, because a lazy
 * `[^}]*` regex would truncate `@layer base` at its first inner `}`. Anchoring to
 * a line start, because globals.css opens with
 * `@custom-variant dark (&:is(.dark *));` — a substring search for ".dark" lands
 * inside *that*, and the next `{` after it belongs to `:root`. The dark block
 * would then be silently extracted as the light one, and the extension's dark
 * theme would render in light colors with nothing failing.
 */
function extractBlock(css, header) {
  const anchored = new RegExp(`^${header.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{`, "m")
  const found = anchored.exec(css)
  if (!found) throw new Error(`sync-theme: no "${header}" block in ${SOURCE}`)
  const start = found.index
  const open = css.indexOf("{", start)
  if (open === -1) throw new Error(`sync-theme: "${header}" has no opening brace`)

  let depth = 0
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++
    else if (css[i] === "}") {
      depth--
      if (depth === 0) return css.slice(open + 1, i)
    }
  }
  throw new Error(`sync-theme: "${header}" block is never closed`)
}

/** `--name: value;` lines, in source order, minus the excluded families. */
function declarations(blockBody) {
  const out = []
  for (const line of blockBody.split("\n")) {
    const match = line.match(/^\s*--([\w-]+)\s*:\s*(.+?);\s*$/)
    if (!match) continue
    const [, name, value] = match
    if (EXCLUDED.test(name)) continue
    out.push([name, value])
  }
  if (out.length === 0) throw new Error("sync-theme: block yielded no declarations")
  return out
}

const render = (decls, indent) =>
  decls.map(([name, value]) => `${" ".repeat(indent)}--${name}: ${value};`).join("\n")

const css = readFileSync(SOURCE, "utf8")
const rootDecls = declarations(extractBlock(css, ":root"))
const darkDecls = declarations(extractBlock(css, ".dark"))
const themeDecls = declarations(extractBlock(css, "@theme inline"))

const generated = `/* GENERATED by scripts/sync-theme.mjs — do not edit by hand.
   Run \`pnpm sync:theme\` after changing tokens in web/app/globals.css.

   Shared shadcn/ui design tokens for the Glint extension (popup + content-script
   UI). chart-* and sidebar-* tokens are omitted: the extension has no charts and
   no shadcn sidebar. Neither tw-animate-css nor shadcn/tailwind.css is imported —
   neither is a dependency of extension/package.json. */

:root {
${render(rootDecls, 4)}
}

/* The extension does not follow the OS theme. extension/lib/theme.ts stamps
   data-theme on <html>; the default is light. */
:root[data-theme="dark"] {
${render(darkDecls, 4)}
}

@theme inline {
${render(themeDecls, 4)}
}
`

const checkOnly = process.argv.includes("--check")
const current = (() => {
  try {
    return readFileSync(TARGET, "utf8")
  } catch {
    return null
  }
})()

// Normalize line endings before comparing. Git is configured to check out CRLF
// on this repo, so a byte comparison against LF-generated output would report
// drift on every Windows checkout.
const same = current !== null && current.replace(/\r\n/g, "\n") === generated

if (checkOnly) {
  if (same) {
    console.log("sync-theme: extension/styles/theme.css is up to date")
    process.exit(0)
  }
  console.error(
    "sync-theme: extension/styles/theme.css is out of sync with web/app/globals.css.\n" +
      "Run `pnpm sync:theme` and commit the result."
  )
  process.exit(1)
}

if (same) {
  console.log("sync-theme: extension/styles/theme.css already up to date")
} else {
  writeFileSync(TARGET, generated)
  console.log("sync-theme: wrote extension/styles/theme.css")
}
